version: '3.5'
services:

  wildfly1:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_1
        CLUSTER_PW: secret_password
    image: wildfly_1
    ports:
    - 8081:8085
    networks:
      wildfly_network:
      
networks:
  wildfly_network:
    ipam:
      driver: default